### ISSUE TITLE
Plugin [spatie-laravel-translatable] is not registered for panel [admin].

### ISSUE THREAD

**Issue by iammuttaqi** [tomatophp/filament-cms#1]
![image](https://github.com/tomatophp/filament-cms/assets/44245907/24d3a858-f6c7-4840-b887-782031bcd73a)

**Comment by fadymondy** [comment]
@iammuttaqi fixed can you check, please?

**Comment by iammuttaqi** [comment]
working fine now

**Comment by fadymondy** [comment]
@iammuttaqi thanks for your support and testing.
