### ISSUE TITLE
->defaultLocales applied only in posts

### ISSUE THREAD

**Issue by luigirossidev** [tomatophp/filament-cms#14]
Hi,
If i set plugin in this way:
`
FilamentCMSPlugin::make()
                    ->useCategory()
                    ->usePost()
                    ->allowExport()
                    ->allowImport()
                    ->defaultLocales(['it', 'en'])
`
   
and i go to categories, the selection remains in english and arabic. Posts are fine.

**Comment by fadymondy** [comment]
fixed on the last version.
