### ISSUE TITLE
Class "Spatie\LaravelSettings\Migrations\SettingsMigration" not found

### ISSUE THREAD

**Issue by iammuttaqi** [tomatophp/filament-cms#2]
![Screenshot 2024-06-19 at 9 10 22 PM](https://github.com/tomatophp/filament-cms/assets/44245907/44f02e6b-1e75-4961-b5bc-4e10b11ada07)

**Comment by fadymondy** [comment]
@iammuttaqi  check now please

**Comment by iammuttaqi** [comment]
working fine now. thanks
