### ISSUE TITLE
Error on comments Table

### ISSUE THREAD

**Issue by xuchengliang-poper** [tomatophp/filament-cms#5]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jueli.comments' doesn't exist (Connection: mysql, SQL: select count(*) as aggregate from `comments` where `comments`.`content_type` = TomatoPHP\FilamentCms\Models\Post and `comments`.`content_id` = 1 and `comments`.`content_id` is not null)

**Comment by fadymondy** [comment]
it's looks like you don't allow the comments feature on the config

```php
return [
    'features' => [
       'comments' => true
    ]
];
```

and than refresh your migration

**Comment by xuchengliang-poper** [comment]
@3x1io thanks for your reply  Yeah, it's been resolved.

**Comment by xuchengliang-poper** [comment]
@3x1io this item's default value shouldn't be true?

**Comment by fadymondy** [comment]
@xuchengliang-eng i think so, i will make it true be default

**Comment by fadymondy** [comment]
it's done now thanks for your report.
