### ISSUE TITLE
getting PSR-4 error for the GenerateSection Class

### ISSUE THREAD

**Issue by maxx-nagar** [tomatophp/filament-cms#6]
while installing this plugin, i am getting this error message "Class TomatoPHP\FilamentCms\Services\GenerateSection located in E:/affixpress-test/example-app/example-app/vendor/tomatophp/filament-cms/src\Generator\GenerateSection.php does not comply with psr-4 autoloading standard. Skipping."

because of this error i am unable to add theme and pages to filementphp app

**Comment by fadymondy** [comment]
i will check it ASAP.

**Comment by fadymondy** [comment]
fixed on the v1.0.12
