### ISSUE TITLE
Error after install the Plugin (SpatieMediaLibraryImageColumn)

### ISSUE THREAD

**Issue by MCS-Technology** [tomatophp/filament-cms#7]
Hi, after install the plugin, i see Categories and Posts Menus, when i click on Posts i see this error:

`Method Filament\Tables\Columns\SpatieMediaLibraryImageColumn::hasRelationship does not exist.`

Laravel v10.48.4 / Filament v: 3.2

**Comment by fadymondy** [comment]
hi @MCS-Technology can you share the full error tracing?

**Comment by MCS-Technology** [comment]
> hi @MCS-Technology can you share the full error tracing?

just this message there are no other lines... see that
![image](https://github.com/user-attachments/assets/c5357543-5658-4ab5-b964-f79f16fee4a8)

**Comment by eko2601** [comment]
check the spatie/laravel-medialibrary version, if using v10, then use this https://spatie.be/docs/laravel-medialibrary/v10/installation-setup
hope it can help

**Comment by fadymondy** [comment]
hi @MCS-Technology i think it's something related to SpatieMediaLibarary, so try to check if you are install it fine
